In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.2'

In [5]:
list_array_a = [2, 4, 6, 8]
list_array_b = [2, 2, 1, 1]
 
print("array from a list:", list_array_a)
print("array from b list:", list_array_b)

array from a list: [2, 4, 6, 8]
array from b list: [2, 2, 1, 1]


In [7]:
list_array_a + list_array_b

[2, 4, 6, 8, 2, 2, 1, 1]

In [10]:
list_array_a * list_array_b

TypeError: can't multiply sequence by non-int of type 'list'

In [11]:
np_array_a1 = np.array(list_array_a)
print(np_array_a1)

np_array_b1 = np.array(list_array_b)
print(np_array_a1)

[2 4 6 8]
[2 4 6 8]


In [12]:
np_array_a1, np_array_b1

(array([2, 4, 6, 8]), array([2, 2, 1, 1]))

In [14]:
print(np_array_a1[2:])
print(np_array_b1[:2])

[6 8]
[2 2]


In [16]:
np_array_a2 = np.array([[1, 2, 3], [4, 5, 6]])
np_array_a2

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
np_array_b2 = np.array([[.1, .2, .3], [.4, .5, .6]])
np_array_b2

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6]])

In [20]:
print(np_array_a1.shape)
print(np_array_a2.shape)
print(np_array_b1.shape)
print(np_array_b2.shape)

np_array_a14 = np.array([[10, 20, 30, 40]])
np_array_a41 = np.array([[5], [10], [15], [20]])
print(np_array_a14, np_array_a14.shape)
print(np_array_a41, np_array_a41.shape)

(4,)
(2, 3)
(4,)
(2, 3)
[[10 20 30 40]] (1, 4)
[[ 5]
 [10]
 [15]
 [20]] (4, 1)


In [24]:
np_array_zeros1 = np.zeros(5)
np_array_zeros2 = np.zeros((3, 4))
                           
print(np_array_zeros1)
print(np_array_zeros2)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [26]:
zeros = np.zeros((100, 100))
print(zeros)
print(zeros.shape)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(100, 100)


In [28]:
np_array_ones1 = np.ones(10)
np_array_ones2 = np.ones((10, 3))

print(np_array_ones1)
print(np_array_ones2)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [29]:
# return number of dimension of an array
print(np_array_zeros1.ndim)
print(np_array_zeros2.ndim)

1
2


In [31]:
# return size of an array
print(np_array_a14.size)
print(np_array_ones2.size)

4
30


In [35]:
# array range
np_arange10 = np.arange(10)
print(np_arange10)

np_arange20 = np.arange(0, 20, 2)
print(np_arange20)

np_arange_desc = np.arange(50, 0, -5)
print(np_arange_desc)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]
[50 45 40 35 30 25 20 15 10  5]


In [37]:
arr = np.append(np_arange10, np_arange20)
np.append(arr, np_arange_desc)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  0,  2,  4,  6,  8, 10, 12,
       14, 16, 18, 50, 45, 40, 35, 30, 25, 20, 15, 10,  5])

In [38]:
np.append(np_array_a2, np_array_b2)

array([1. , 2. , 3. , 4. , 5. , 6. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6])

In [40]:
np.append(np_array_a2, np_array_b2, axis=0)

array([[1. , 2. , 3. ],
       [4. , 5. , 6. ],
       [0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6]])

In [41]:
np.append(np_array_a2, np_array_b2, axis=1)

array([[1. , 2. , 3. , 0.1, 0.2, 0.3],
       [4. , 5. , 6. , 0.4, 0.5, 0.6]])

In [42]:
np.append(np_array_a2, np_array_zeros2)

array([1., 2., 3., 4., 5., 6., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

In [43]:
np.append(np_array_a2, np_array_zeros2 axis=0)

SyntaxError: invalid syntax (<ipython-input-43-0a3b7c8dec4c>, line 1)

In [44]:
np.sort(np_arange_desc)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [46]:
np_array_a2b2 = np.append(np_array_a2, np_array_b2, axis=0)
print(np_array_a2b2)

[[1.  2.  3. ]
 [4.  5.  6. ]
 [0.1 0.2 0.3]
 [0.4 0.5 0.6]]


In [47]:
np.sort(np_array_a2b2 ,axis=0)

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6],
       [1. , 2. , 3. ],
       [4. , 5. , 6. ]])

In [49]:
np_array_a3 = np.array(
    [
        [
            [9, 3, 1, 5],
            [1, 2, 2, 3],
            [4, 10, 3, 2]
        ],
        [
            [19, 3, 1, 50],
            [13, 1, 21, 13],
            [4, 10, 0, 2]
        ],
        [
            [100, 2, 3, 3],
            [9, 3, 4, 3],
            [1, 1, 2, 0]
        ],
    ]
)

print(np_array_a3)
print("shape:", np_array_a3.shape)
print("ndim:", np_array_a3.ndim)
print("size:", np_array_a3.size)

[[[  9   3   1   5]
  [  1   2   2   3]
  [  4  10   3   2]]

 [[ 19   3   1  50]
  [ 13   1  21  13]
  [  4  10   0   2]]

 [[100   2   3   3]
  [  9   3   4   3]
  [  1   1   2   0]]]
shape: (3, 3, 4)
ndim: 3
size: 36


In [50]:
type(np_array_a3)

numpy.ndarray

In [52]:
np.reshape(np_array_a3, (6, 6))

array([[  9,   3,   1,   5,   1,   2],
       [  2,   3,   4,  10,   3,   2],
       [ 19,   3,   1,  50,  13,   1],
       [ 21,  13,   4,  10,   0,   2],
       [100,   2,   3,   3,   9,   3],
       [  4,   3,   1,   1,   2,   0]])

In [53]:
np_array_a3.reshape((6, 6))

array([[  9,   3,   1,   5,   1,   2],
       [  2,   3,   4,  10,   3,   2],
       [ 19,   3,   1,  50,  13,   1],
       [ 21,  13,   4,  10,   0,   2],
       [100,   2,   3,   3,   9,   3],
       [  4,   3,   1,   1,   2,   0]])

In [54]:
np_array_a3.reshape((4, 4))

ValueError: cannot reshape array of size 36 into shape (4,4)

In [55]:
np_array_a3.reshape((4, 10))

ValueError: cannot reshape array of size 36 into shape (4,10)

In [57]:
np_array_a3.reshape((3, 3, 2, 2))

array([[[[  9,   3],
         [  1,   5]],

        [[  1,   2],
         [  2,   3]],

        [[  4,  10],
         [  3,   2]]],


       [[[ 19,   3],
         [  1,  50]],

        [[ 13,   1],
         [ 21,  13]],

        [[  4,  10],
         [  0,   2]]],


       [[[100,   2],
         [  3,   3]],

        [[  9,   3],
         [  4,   3]],

        [[  1,   1],
         [  2,   0]]]])

In [58]:
np_array_a3.reshape((3, 3, 2, 2, 1))

array([[[[[  9],
          [  3]],

         [[  1],
          [  5]]],


        [[[  1],
          [  2]],

         [[  2],
          [  3]]],


        [[[  4],
          [ 10]],

         [[  3],
          [  2]]]],



       [[[[ 19],
          [  3]],

         [[  1],
          [ 50]]],


        [[[ 13],
          [  1]],

         [[ 21],
          [ 13]]],


        [[[  4],
          [ 10]],

         [[  0],
          [  2]]]],



       [[[[100],
          [  2]],

         [[  3],
          [  3]]],


        [[[  9],
          [  3]],

         [[  4],
          [  3]]],


        [[[  1],
          [  1]],

         [[  2],
          [  0]]]]])

In [60]:
np_array_a1[:, np.newaxis]

array([[2],
       [4],
       [6],
       [8]])

In [61]:
np.expand_dims(np_array_a1, axis=1)

array([[2],
       [4],
       [6],
       [8]])

In [62]:
np.expand_dims(np_array_a1, axis=0)

array([[2, 4, 6, 8]])

In [65]:
np_array_a1[None, :, None, None]

array([[[[2]],

        [[4]],

        [[6]],

        [[8]]]])

In [66]:
np_array_a1[np.newaxis, :, np.newaxis, np.newaxis]

array([[[[2]],

        [[4]],

        [[6]],

        [[8]]]])

In [71]:
print(np_array_zeros1.reshape((1, 5)))
print(np_array_zeros1.reshape((5,1)))
print(np_array_zeros1.reshape((1, 5, 1)))

[[0. 0. 0. 0. 0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[[0.]
  [0.]
  [0.]
  [0.]
  [0.]]]


In [76]:
size = np_array_a2.size
new_size = 10
np.append(np_array_a2, np.zeros(new_size - size)).reshape((2, 5))

array([[1., 2., 3., 4., 5.],
       [6., 0., 0., 0., 0.]])

In [77]:
np_array_c1 = np.arange(0, 1.8, .2)
print(np_array_c1, np_array_c1.shape, np_array_c1,size)

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6] (9,) [0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6] 6


In [78]:
# ambil median
# median -> nilai tengah -> n=9, nilai tengah ke-4
# cari tahu n -> len()
# n // 2
n = np_array_c1.shape[0]
print("number of item:", n)

med = np_array_c1[n // 2]
print("median:", med)

number of item: 9
median: 0.8


In [79]:
list_array_b2 = np_array_b2.tolist()
print(list_array_b2, type(list_array_b2))

[[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]] <class 'list'>


In [83]:
list_array_b2[0][:2], list_array_b2[1][:2]

([0.1, 0.2], [0.4, 0.5])

In [84]:
np_array_b2[:, :2]

array([[0.1, 0.2],
       [0.4, 0.5]])

In [85]:
np_array_b2[:, 0]

array([0.1, 0.4])

In [86]:
np_array_b2[:, 1]

array([0.2, 0.5])

In [100]:
np_array_b2[:, [0, 2]], np_array_b2[:, ::2]

(array([[0.1, 0.3],
        [0.4, 0.6]]),
 array([[0.1, 0.3],
        [0.4, 0.6]]))

In [103]:
np_array_c2 = np_array_a3.reshape((3, 12))
print(np_array_c2)

[[  9   3   1   5   1   2   2   3   4  10   3   2]
 [ 19   3   1  50  13   1  21  13   4  10   0   2]
 [100   2   3   3   9   3   4   3   1   1   2   0]]


In [104]:
np_array_c2[np_array_c2 % 3 == 0]

array([ 9,  3,  3,  3,  3, 21,  0,  3,  3,  9,  3,  3,  0])

In [107]:
np_array_a1, np_array_a1[[True, False, True, True]], np_array_a1[[0, 2, 3]]

(array([2, 4, 6, 8]), array([2, 6, 8]), array([2, 6, 8]))

In [105]:
np_array_c2 % 3 == 0

array([[ True,  True, False, False, False, False, False,  True, False,
        False,  True, False],
       [False,  True, False, False, False, False,  True, False, False,
        False,  True, False],
       [False, False,  True,  True,  True,  True, False,  True, False,
        False, False,  True]])

In [108]:
np.concatenate((np_array_c2, np_array_c2, np_array_c2, np_array_c2), axis=0)

array([[  9,   3,   1,   5,   1,   2,   2,   3,   4,  10,   3,   2],
       [ 19,   3,   1,  50,  13,   1,  21,  13,   4,  10,   0,   2],
       [100,   2,   3,   3,   9,   3,   4,   3,   1,   1,   2,   0],
       [  9,   3,   1,   5,   1,   2,   2,   3,   4,  10,   3,   2],
       [ 19,   3,   1,  50,  13,   1,  21,  13,   4,  10,   0,   2],
       [100,   2,   3,   3,   9,   3,   4,   3,   1,   1,   2,   0],
       [  9,   3,   1,   5,   1,   2,   2,   3,   4,  10,   3,   2],
       [ 19,   3,   1,  50,  13,   1,  21,  13,   4,  10,   0,   2],
       [100,   2,   3,   3,   9,   3,   4,   3,   1,   1,   2,   0],
       [  9,   3,   1,   5,   1,   2,   2,   3,   4,  10,   3,   2],
       [ 19,   3,   1,  50,  13,   1,  21,  13,   4,  10,   0,   2],
       [100,   2,   3,   3,   9,   3,   4,   3,   1,   1,   2,   0]])

In [109]:
np_array_c2 + np_array_c2

array([[ 18,   6,   2,  10,   2,   4,   4,   6,   8,  20,   6,   4],
       [ 38,   6,   2, 100,  26,   2,  42,  26,   8,  20,   0,   4],
       [200,   4,   6,   6,  18,   6,   8,   6,   2,   2,   4,   0]])

In [110]:
np_array_c2 - np_array_c2

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [111]:
np_array_c2 / np_array_c2

<ipython-input-111-cd24c6aff44e>:1: RuntimeWarning: invalid value encountered in true_divide
  np_array_c2 / np_array_c2


array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., nan,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., nan]])

In [112]:
None, np.nan, type(np.nan)

(None, nan, float)

In [113]:
np_array_c2 * np_array_c2

array([[   81,     9,     1,    25,     1,     4,     4,     9,    16,
          100,     9,     4],
       [  361,     9,     1,  2500,   169,     1,   441,   169,    16,
          100,     0,     4],
       [10000,     4,     9,     9,    81,     9,    16,     9,     1,
            1,     4,     0]])

In [115]:
np_array_c2 * 2

array([[ 18,   6,   2,  10,   2,   4,   4,   6,   8,  20,   6,   4],
       [ 38,   6,   2, 100,  26,   2,  42,  26,   8,  20,   0,   4],
       [200,   4,   6,   6,  18,   6,   8,   6,   2,   2,   4,   0]])

In [116]:
np_array_c2 + 2

array([[ 11,   5,   3,   7,   3,   4,   4,   5,   6,  12,   5,   4],
       [ 21,   5,   3,  52,  15,   3,  23,  15,   6,  12,   2,   4],
       [102,   4,   5,   5,  11,   5,   6,   5,   3,   3,   4,   2]])

In [117]:
np_array_c2 + np_array_c2[0]

array([[ 18,   6,   2,  10,   2,   4,   4,   6,   8,  20,   6,   4],
       [ 28,   6,   2,  55,  14,   3,  23,  16,   8,  20,   3,   4],
       [109,   5,   4,   8,  10,   5,   6,   6,   5,  11,   5,   2]])

In [120]:
np_array_c2

array([[  9,   3,   1,   5,   1,   2,   2,   3,   4,  10,   3,   2],
       [ 19,   3,   1,  50,  13,   1,  21,  13,   4,  10,   0,   2],
       [100,   2,   3,   3,   9,   3,   4,   3,   1,   1,   2,   0]])

In [122]:
np_array_c2.max()
print(np_array_c2.max(axis=1))
print(np_array_c2.max(axis=0))
print(np_array_c2.max(axis=1, keepdims=True))
print(np_array_c2.max(axis=0, keepdims=True))

[ 10  50 100]
[100   3   3  50  13   3  21  13   4  10   3   2]
[[ 10]
 [ 50]
 [100]]
[[100   3   3  50  13   3  21  13   4  10   3   2]]


In [123]:
np_array_a2

array([[1, 2, 3],
       [4, 5, 6]])

In [124]:
np_array_a2.transpose(), np_array_a2.T

(array([[1, 4],
        [2, 5],
        [3, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [125]:
np.dot(np_array_a2, np_array_a2.T)

array([[14, 32],
       [32, 77]])

In [126]:
np.matmul(np_array_a2, np_array_a2.T)

array([[14, 32],
       [32, 77]])

In [127]:
np_array_a2.flatten()

array([1, 2, 3, 4, 5, 6])

In [128]:
np_array_a3.flatten()

array([  9,   3,   1,   5,   1,   2,   2,   3,   4,  10,   3,   2,  19,
         3,   1,  50,  13,   1,  21,  13,   4,  10,   0,   2, 100,   2,
         3,   3,   9,   3,   4,   3,   1,   1,   2,   0])

In [135]:
np.random.randint(10, 100,  size=(2, 2, 3))

array([[[49, 64, 32],
        [86, 19, 77]],

       [[74, 14, 63],
        [35, 92, 55]]])